#10 Narrative Updates
HL7Austria/HL7-AT-FHIR-Core-R5 pull request #11
Opened 2024-07-02 17:42 UTC by regelkraut

updated the index.md file to be up-to-date

Closes #10

2024-07-05 10:11 UTC, oliver-krauss requested changes
See changes in the other PR

2024-07-08 14:20 UTC, gabriel0316 commented
See changes in the other PR

2024-07-10 08:14 UTC, gabriel0316 approved these changes

2024-07-12 07:33 UTC, oliver-krauss approved these changes

2024-07-12 10:37 UTC, merged