Update CONTRIBUTING.md
HL7Austria/HL7-AT-FHIR-Core-R5 pull request #28
Opened 2024-09-19 14:41 UTC by oliver-krauss

See #23

2024-09-19 14:50 UTC, alackerbauer requested changes
Please rename the repository to .github and the file to README.md so it automatically appears on the HL7 Github Organization's landing page.
![Screenshot_20240919-164556_Chrome](https://github.com/user-attachments/assets/eea93125-c7e7-453f-985a-90d8d8cdc252)

2024-09-19 14:57 UTC, oliver-krauss commented
> Please rename the repository to .github and the file to README.md so it automatically appears on the HL7 Github Organization's landing page. ![Screenshot_20240919-164556_Chrome](https://private-user-images.githubusercontent.com/33912849/369050487-eea93125-c7e7-453f-985a-90d8d8cdc252.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTgxMTQsIm5iZiI6MTcyNjc1NzgxNCwicGF0aCI6Ii8zMzkxMjg0OS8zNjkwNTA0ODctZWVhOTMxMjUtYzdlNy00NTNmLTk4NWEtOTBkOGQ4Y2RjMjUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNzRjZTY0YWE0OGQ4ZTBlOTlkMGY1NjkwNGM3MmIyYzdlNDMwNjY5ZTY2ODBjZGJjODQyMzIzN2ZlNWIzMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6_CPvy_TVFZe1bkrAKPLAxVf5O5MUidHZt8iQGHMB_w)

Done, I won't link directly to the contribution guide though, it is extremely long and not suitable for linking

2024-09-23 08:57 UTC, alackerbauer approved these changes

2025-01-08 14:24 UTC, oliver-krauss commented
@regelkraut may i ask you for quick accept then we can merge.

2025-01-08 14:26 UTC, regelkraut approved these changes

2025-01-08 14:30 UTC, merged